[package]
name = "lcs"
version = "0.1.0"
authors = ["Dmicheal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.20"
serde = { version = "1.0.115", features = ["derive"] }
